#pragma once

#include <cstdint>
#include <functional>
#include <string>
#include <vector>

#include "engine/platform/devices/gamepad.hpp"
#include "engine/platform/devices/keys.hpp"

namespace Shard::Engine::Core::Platform {

    enum class OSEventType : uint8_t {
        Quit,                   // the OS asks the application to terminate
        WindowCloseRequested,
        WindowResized,          // size = new framebuffer size in pixels
        WindowMoved,
        WindowFocusGained,
        WindowFocusLost,
        WindowMinimized,
        WindowRestored,
        DisplayScaleChanged,    // scale = new content scale (DPI / 96)
        KeyDown,
        KeyUp,
        TextInput,              // text = UTF-8 characters typed
        MouseMotion,
        MouseButtonDown,
        MouseButtonUp,
        MouseWheel,
        FileDropped,            // text = path of the file
        GamepadConnected,
        GamepadDisconnected,
        GamepadButtonDown,      // deviceId, gamepadButton
        GamepadButtonUp,
        GamepadAxisMotion       // deviceId, gamepadAxis, axisValue
    };

    /// @brief A window system event, translated to the engine's own types so nothing above the platform layer depends on the backend.
    struct OSEvent {
        OSEventType type = OSEventType::Quit;

        int width = 0, height = 0;          // WindowResized
        int x = 0, y = 0;                   // WindowMoved
        float scale = 1.0f;                 // DisplayScaleChanged

        Input::Key key = Input::Key::Space; // KeyDown / KeyUp
        bool repeat = false;                // KeyDown generated by the key repeat

        Input::MouseButton button = Input::MouseButton::Left; // MouseButtonDown / MouseButtonUp
        float mouseX = 0.0f, mouseY = 0.0f; // MouseMotion / MouseButton*: position in the window
        float deltaX = 0.0f, deltaY = 0.0f; // MouseMotion: relative motion. MouseWheel: scroll

        std::string text;                   // TextInput / FileDropped
        uint32_t deviceId = 0;              // Gamepad* : identifies the device (stable while it stays plugged in)
        Input::GamepadButton gamepadButton = Input::GamepadButton::South;
        Input::GamepadAxis gamepadAxis = Input::GamepadAxis::LeftX;
        float axisValue = 0.0f;             // GamepadAxisMotion, normalised : sticks -1..1, triggers 0..1
    };

    using OSEventListener = std::function<void(const OSEvent&)>;

    /// @brief Something that produces OS events and lets several consumers listen to them.
    class OSEventSource {
    public:
        using ListenerId = uint32_t;

        virtual ~OSEventSource() = default;

        /// @brief Registers a listener, called from the thread that pumps the events.
        ListenerId AddEventListener(OSEventListener listener) {
            const ListenerId id = ++m_NextListener;
            m_Listeners.push_back({ id, std::move(listener) });
            return id;
        }

        void RemoveEventListener(ListenerId id) {
            for (auto it = m_Listeners.begin(); it != m_Listeners.end(); ++it)
                if (it->id == id) { m_Listeners.erase(it); return; }
        }

    protected:
        void DispatchEvent(const OSEvent& event) {
            // Index based: a listener may register another one while it runs.
            for (size_t i = 0; i < m_Listeners.size(); ++i) {
                OSEventListener callback = m_Listeners[i].callback;
                if (callback) callback(event);
            }
        }

    private:
        struct Entry { ListenerId id; OSEventListener callback; };
        std::vector<Entry> m_Listeners;
        ListenerId m_NextListener = 0;
    };
}
